src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use App\Tools\CastableToArray;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 *
 * @ApiResource(normalizationContext={"groups"={"user"}, "enable_max_depth"=true}, attributes={"order"={"name", "firstName"}})
 * @ApiFilter(DateFilter::class, properties={"updatedAt"})
 * @ApiFilter(SearchFilter::class, properties={"id": "exact", "username": "exact", "name":"partial", "firstName":"partial", "status"="exact"})
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{

    use CastableToArray;
    /**
     * @Groups({"message", "user"})
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups({"message", "user", "friendship"})
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $roles = [];

    /**
     * @Groups({"message", "user", "friendship"})
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @Groups({"message", "user", "friendship"})
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @Groups({"message", "user"})
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @MaxDepth(1)
     * @Groups({"user"})
     * @ORM\OneToMany(targetEntity="Friendship", mappedBy="user")
     */
    private $friends;

    /**
     *
     * @MaxDepth(1)
     * @Groups({"user"})
     * @ORM\OneToMany(targetEntity="Friendship", mappedBy="friend")
     */
    private $friendsWithMe;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="owner", orphanRemoval=true)
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="toUser")
     */
    private $receivedMessages;

    /**
     * @var array
     */
    private $allMyFriends;

    public function __construct()
    {
        $this->friends = new ArrayCollection();
        $this->friendsWithMe = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->allMyFriends = [];
        
        $this->receivedMessages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|Friendship[]
     */
    public function getFriends()
    {
        return $this->friends;
    }

    public function getCompleteName()
    {
        return $this->getName().' '.$this->getFirstName();
    }
    /**
     * @return Collection|Friendship[]
     */
    public function getFriendsWithMe()
    {
        return $this->friendsWithMe;
    }

    public function addFriendship(Friendship $friendship)
    {
        $this->friends->add($friendship);
        $friendship->getFriend()->addFriendshipWithMe($friendship);
    }

        public function addFriendshipWithMe(Friendship $friendship)
    {
        $this->friendsWithMe->add($friendship);
    }

    public function addFriend(User $friend)
    {
        $fs = new Friendship();
        $fs->setUser($this);
        $fs->setFriend($friend);
        // set defaults
        $fs->setIsAccepted(true);

        $this->addFriendship($fs);
    }

    /**
     * @return array
     */
    public function getAllMyFriends(): array
    {
        return $this->allMyFriends;
    }

    /**
     * @param array $allMyFriends
     */
    public function setAllMyFriends(array $allMyFriends): void
    {
        $this->allMyFriends = $allMyFriends;
    }


    /**
     * @return Collection|Message[]
     */
    public function getMessages()
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setOwner($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getOwner() === $this) {
                $message->setOwner(null);
            }
        }

        return $this;
    }

    public function getNumberOfMessages()
    {
        return sizeof($this->messages);
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }


    public function setObjectFromArray($array = [])
    {
        if (!is_null($array)) {
            foreach ($array as $property => $value) {
                if ($value) {
                    if (property_exists(get_class($this), $property)) {
                        if($property == 'message' && is_array($value)) {
                            $message = new Message();
                            $message->setObjectFromArray($value);
                            $this->addMessage($message);
                        } elseif ($property == 'connections' && is_array($value)) {
                            $connection = new User();
                            $connection->setObjectFromArray($value);
                            $this->addConnection($connection);
                        } elseif($property == 'createdAt' || $property == 'updatedAt' || $property == 'deletedAt') {
                            if($value) {
                                $this->$property = new \DateTime($value);
                            }
                        } else {
                            $this->$property = $value;
                        }
                    }
                }
            }
        }
    }

    /**
     * @return Collection|Message[]
     */
    public function getReceivedMessages(): Collection
    {
        return $this->receivedMessages;
    }

    public function addReceivedMessage(Message $receivedMessage): self
    {
        if (!$this->receivedMessages->contains($receivedMessage)) {
            $this->receivedMessages[] = $receivedMessage;
            $receivedMessage->setToUser($this);
        }

        return $this;
    }

    public function removeReceivedMessage(Message $receivedMessage): self
    {
        if ($this->receivedMessages->contains($receivedMessage)) {
            $this->receivedMessages->removeElement($receivedMessage);
            // set the owning side to null (unless already changed)
            if ($receivedMessage->getToUser() === $this) {
                $receivedMessage->setToUser(null);
            }
        }

        return $this;
    }


}

templates/client/current_user.html.twig
<div class="col-8">
    <div class="media">
        <img class="align-self-center mr-3" style="width: 40px; height: 40px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgeCcQUwGikScGUriqzG6uY4DvGdfJqq0jBVHqR756UNlw-mcbcg" alt="Generic placeholder image">
        <div class="media-body">
            <h6 class="mt-0">{{ currentUser.username }}<small> - {{ currentUser.allMyFriends|length }} ami(s)</small></h6>
            <p>
                <button class="btn btn-link btn-primary"  data-toggle="modal" data-target="#newMessageModal"> New message </button>
                {% if currentUser.username != timelineOwner.username %}
                    <a href="{{ path('index') }}" class="card-link">Voir ma timeline</a>
                {% endif %}
            </p>
        </div>
    </div>
</div>

<div class="col-4">
    <div class="row">
        <div class="col-12 mb-3">
        {% if currentUser.allMyFriends|length > 0 %}
        <button type="button" class="btn  btn-primary btn-link btn-block" data-toggle="modal" data-target="#friendsModalLong">
            Friend list...
        </button>
        {% else %}
            It seems you don't have any friend yet... Click on the user list link below and choose who are your friends ..
        {% endif %}
        </div>
        <div class="col-12">
            {% if userList is defined %}
                {% include 'client/user_list.html.twig' %}
            {% endif %}
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="friendsModalLong" tabindex="-1" role="dialog" aria-labelledby="friendsModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="friendsModalLongTitle">Friend List</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="list-unstyled">
                    {% for friend in currentUser.allMyFriends %}
                        <li class="media col-12">
                            <img class="align-self-center mr-3" style="width: 25px; height: 25px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgeCcQUwGikScGUriqzG6uY4DvGdfJqq0jBVHqR756UNlw-mcbcg" alt="Generic placeholder image">
                            <div class="media-body">
                                <h7 class="mt-0 mb-1">{{ friend.username }}</h7>
                                <small class="text-muted">{{ friend.name }} {{ friend.firstName }}</small>
                                <span class="link-timeline link-timeline_{{ friend.id }} badge badge-success pointer" data-user="{{ path('index', {'id': friend.id} ) }}">Voir sa timeline...</span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="newMessageModal" tabindex="-1" role="dialog" aria-labelledby="newMessageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newMessageModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{ form_start(newMessageForm) }}
            <div class="modal-body">
                <div class="row">
                    <div class="col-3">
                        {{ form_label(newMessageForm.toUser) }}
                    </div>
                    <div class="col-9">
                        {{ form_widget(newMessageForm.toUser) }}
                    </div>
                    <div class="col-3">
                        {{ form_label(newMessageForm.subject) }}
                    </div>
                    <div class="col-9">
                        {{ form_widget(newMessageForm.subject) }}
                    </div>
                    <div class="col-3">
                        {{ form_label(newMessageForm.bodyMessage) }}
                    </div>
                    <div class="col-9">
                        {{ form_widget(newMessageForm.bodyMessage) }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                {{ form_widget(newMessageForm.save) }}
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            {{ form_end(newMessageForm) }}
        </div>
    </div>
</div>

<div class="modal fade" id="editMessageModal" tabindex="-1" role="dialog" aria-labelledby="editMessageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editMessageModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{ form_start(editMessageForm) }}
            <div class="modal-body">
                <div class="row">
                    <div class="col-3">
                        {{ form_label(editMessageForm.toUser) }}
                    </div>
                    <div class="col-9">
                        {{ form_widget(editMessageForm.toUser) }}
                    </div>
                    <div class="col-3">
                        {{ form_label(editMessageForm.subject) }}
                    </div>
                    <div class="col-9">
                        {{ form_widget(editMessageForm.subject) }}
                    </div>
                    <div class="col-3">
                        {{ form_label(editMessageForm.bodyMessage) }}
                    </div>
                    <div class="col-9">
                        {{ form_widget(editMessageForm.bodyMessage) }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                {{ form_widget(editMessageForm.save) }}
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            {{ form_end(editMessageForm) }}
        </div>
    </div>
</div>

templates/client/index.html.twig
{% extends  'base.html.twig' %}

{% block user %}
    {% include 'client/current_user.html.twig' %}

{% endblock %}
{% block message_wall %}
    <div class="row messages-wall">
    {% if myMessages is defined %}
        {% include 'client/messages.html.twig' %}
    {% endif %}
    </div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script type="application/javascript">
        $(document).ready(function () {
            // Formulaire d'ajout d'amis
            $('.create-friend').on('click', function () {
                let friend = $(this).data('friendid')
                $('#friend_form_friend').val(friend)
                $('form[name="friend_form"]').submit()
            })
            $('.reply-msg').on('hide.bs.collapse', function () {
                let btnId = $(this).data('from');
                $('#'+btnId).text('See the replies...')
            })

            $('.reply-msg').on('show.bs.collapse', function () {
                let btnId = $(this).data('from');
                $('#'+btnId).text('Hide the replies...')
            })
            $('.link-timeline').on('click', function (event) {
                let url = $(this).data('user')
                window.location = url
            })

            $(document).ready(function () {
                $('#editMessageModal').on('show.bs.modal', function (event) {
                    // Formulaire de reponse au messages
                    var button = $(event.relatedTarget) // Button that triggered the modal

                    var subjectDivId = button.data('message_subject_id')
                    var bodyDivId = button.data('message_body_id')
                    var idMsg = button.data('message_id')
                    var idToUser = button.data('message_touser_id')
                    var userName = button.data('toname')
                    var idOwner = button.data('message_owner_id')
                    var modal = $(this)
                    modal.find('.modal-title').text('Edit message to ' + userName)

                    console.log(idMsg);
                    console.log(idOwner);

                    $('#form_edit_message_subject').val($('#'+subjectDivId).text())
                    $('#form_edit_message_bodyMessage').val($('#'+bodyDivId).text())

                    $("#form_edit_message_toUser option").filter(function() {
                        //may want to use $.trim in here

                        return $(this).val() == idToUser;
                    }).prop('selected', true);

                    //$('').val(idToUser)
                    $('#form_edit_message_owner').val(idOwner)
                    $('#form_edit_message_id').val(idMsg)
                })
            })
        })
        $(document).ready(function () {
            $('#replyModal').on('show.bs.modal', function (event) {
                // Formulaire de reponse au messages
                var button = $(event.relatedTarget) // Button that triggered the modal

                var subject = button.data('contentsubject') // Extract info from data-* attributes
                var owner = button.data('owner') // Extract info from data-* attributes
                var toUser = button.data('touser') // Extract info from data-* attributes
                var userName = button.data('toname')
                var parent = button.data('parent') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                modal.find('.modal-title').text('New message to ' + userName)
                $('#reply_form_subject').val('Re: ' + subject)
                $('#reply_form_parentMessage').val(parent)
                $('#reply_form_toUser').val(toUser)
                $('#reply_form_owner').val(owner)
            })

            $('#saving_form').on('click', function () {
                $("#reply_form").submit()
            })
        })
    </script>
{% endblock %}

templates/client/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mb-5"></div>
    <div class="row justify-content-md-center card card-heayder">
        <div class="col col-lg-2"></div>
        <div class="col-md-auto card-title text-center">Veuillez vous identifier ou créer un compte...</div>
        <div class="col col-lg-2"></div>
        <div class="col col-lg-2"></div>
        <div class="col-md-auto card-body text-center">
            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
        <div class="col col-lg-2"></div>
        <div class="col-12">&nbsp;</div>
        <div class="col-sm pb-2">&nbsp;</div>
        <div class="col-sm pb-4 card-link h6 small">
            <a href="{{ path('subscribe') }}">Créer un compte</a>
        </div>
        <div class="col-sm ">&nbsp;</div>
    </div>

{% endblock %}

templates/client/messages.html.twig
<div class="col-12">
    {% if timelineOwner.username == currentUser.username %}
        <h5 class="card-title">Ma Timeline</h5>
    {% else %}
        <div class="media">
            <img class="align-self-center mr-3" style="width: 25px; height: 25px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgeCcQUwGikScGUriqzG6uY4DvGdfJqq0jBVHqR756UNlw-mcbcg" alt="Generic placeholder image">
            <div class="media-body">
                <h6 class="mt-0"> TimeLine de {{ timelineOwner.username }}</h6>
            </div>
        </div>
    {% endif %}
</div>
{% for message in myMessages %}
    <div class="card card-body col-12 mb-5">
        <div class="row justify-content-between">
            <div class="col-4">
                <p class="card-text text-left">
                    <small>
                        le {{ message.updatedAt|date("d/m/Y \\à H:i:s") }} {{ currentUser.username == message.owner.username ? 'You': message.owner.completeName }} wrote a message to {{ currentUser.username == message.toUser.username ? 'you': message.toUser.completeName }}.
                    </small>
                </p>
            </div>
            <div class="col-4">
                <p class="card-text text-right">
                {% if message.owner.username == currentUser.username %}
                    <small>
                        <a href="#" class="edit-message text-right" data-toggle="modal" data-target="#editMessageModal" data-toname="{{ message.toUser.username }}" data-message_subject_id="message_subject_{{ message.id }}" data-message_body_id="message_body_{{ message.id }}" data-message_touser_id="{{ message.toUser.id }}" data-message_owner_id="{{ message.owner.id }}" data-message_id="{{ message.id }}">
                            edit
                        </a>
                    </small>
                {% endif %}
            </p>
            </div>
        </div>
        <h5 class="card-title" id="message_subject_{{ message.id }}">{{ message.subject }}</h5>
        <p class="card-text" id="message_body_{{ message.id }}">{{ message.bodyMessage }}</p>
        <div class="row">
            {% include 'client/reply_form.html.twig' %}
            {% include 'client/reply.html.twig' %}
        </div>
    </div>
    {#<div class="card-footer col-12">#}
        {#&nbsp;#}
    {#</div>#}
{% endfor %}

templates/client/reply.html.twig
{% if message.replies|length > 0 %}
    <div class="col-6">
        <button class="btn btn-primary btn-link btn-block mb-2 reply-collapse" id="collapse_btn_{{ message.id }}" type="button" data-toggle="collapse" data-target="#collapseRep_{{ message.id }}" aria-expanded="false" aria-controls="collapseRep_{{ message.id }}">
            See the replies...
        </button>
    </div>
    <div class="col-12">
        <div class="collapse mb-3 reply-msg" id="collapseRep_{{ message.id }}" data-from="collapse_btn_{{ message.id }}">
    {% for reply in message.replies %}
            <div class="card card-header">
                <p class="small">le {{ reply.updatedAt|date("d/m/Y \\à H:i:s") }} {{ currentUser.username == reply.owner.username ? 'vous avez répondu': reply.owner.getCompleteName()~' vous a répondu' }} </p>
                <h5 class="card-title">{{ reply.subject }}</h5>
                <p class="card-text">{{ reply.bodyMessage }}</p>
            </div>
    {% endfor %}
        </div>
    </div>
{% endif %}

templates/client/reply_form.html.twig
<div class="col-6">
    <button type="button" class="btn btn-primary btn-link btn-block mb-4" data-toggle="modal" data-target="#replyModal" data-contentsubject="{{ message.subject }}" data-parent="{{ message.id }}" data-owner="{{ currentUser.id }}" data-toUser="{{ message.owner.id }}" data-toName="{{ message.owner.username }}">
        Reply
    </button>

    <div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="replyModalLabel">New message</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="reply_form" name="reply_form" method="post">
                        <div id="reply_form">
                            <div>
                                <label for="reply_form_subject" class="required">Subject</label>
                                <input type="text" id="reply_form_subject" name="reply_form[subject]" required="required">
                            </div>
                            <div>
                                <label for="reply_form_bodyMessage" class="required">Body message</label>
                                <textarea id="reply_form_bodyMessage" name="reply_form[bodyMessage]" required="required"></textarea>
                            </div>
                            <input type="hidden" id="reply_form_parentMessage" name="reply_form[parentMessage]" value="">
                            <input type="hidden" id="reply_form_toUser" name="reply_form[toUser]" value="">
                            <input type="hidden" id="reply_form_owner" name="reply_form[owner]" value="">
                            <div style="display:none">
                                <button type="submit" id="reply_form_save" name="reply_form[save]">Answer</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="saving_form" class="btn btn-success">Send message</button>
                </div>
            </div>
        </div>
    </div>

</div>

templates/client/subscribe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello !{% endblock %}

{% block body %}

    <div class="row mb-5"></div>
    <div class="row justify-content-center card card-body">
       <div class="col-12 text-center">
           <p class="card-title">Formulaire de souscription </p>
       </div>
        <div class="col-12">
            {{ form_start(form) }}
            <div class="row justify-center">
                <div class="col-5 text-right">
                    {{ form_label(form.username) }}
                </div>
                <div class="col-5 text-left">
                    {{ form_widget(form.username) }}
                </div>
                <div class="col-5 text-right">
                    {{ form_label(form.password) }}
                </div>
                <div class="col-5 text-left">
                    {{ form_widget(form.password) }}
                </div>
                <div class="col-5 text-right">
                    {{ form_label(form.name) }}
                </div>
                <div class="col-5 text-left">
                    {{ form_widget(form.name) }}
                </div>
                <div class="col-5 text-right">
                    {{ form_label(form.firstname) }}
                </div>
                <div class="col-5 text-left">
                    {{ form_widget(form.firstname) }}
                </div>
                <div class="col-12 text-center">
                    {{ form_row(form.save) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
        <div class="col-sm pb-4 card-link h6 small"><a href="{{ path("home") }}"> login </a></div>
    </div>

{% endblock %}